### PR TITLE
Calculate carousel width with margin

### PR DESCRIPTION
**Pull request by KevinBatdorf**
@DavidAnderson684 We'll also test this internally (MR already set up), but I'll give you a nudge on Slack when to merge this GitHub PR in.

This solves two issues with the carousel. 

1. Slideshows with larger margins will skip some slides ([related WP.org support thread](https://wordpress.org/support/topic/carousel-missing-a-slide/)). Note that this PR doesn't affect the workaround provided to the user as mentioned in that support conversation.

2. On load, the dots aren't always properly calculated because the container width isn't always rendered when the `doMath()` method runs. This fix triggers a recalculation at the final moment.

I've also deleted a bunch of files that we don't use in MetaSlider. I did this because this fork is to be used only in MetaSlider and might not work in all use cases _outside_ of MetaSlider. Also, they have build tools that we're not using and the minified version doesn't represent the changes. Changes are only in the `jquery.flexslider.js` file.

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
@KZeni If you can take a look here and see if this also solves your issue? If so it will make it in the next release. 

Thanks!

**Comment by DavidAnderson684** [comment]
@KevinBatdorf Thank you - are you saying it's ready to merge? Or after a bit more testing?

**Comment by KevinBatdorf** [comment]
@DavidAnderson684 Not ready yet. I'll wait for @KZeni to confirm it works (he reported the bug). I'll let you know on Slack.

**Comment by KZeni** [comment]
@KevinBatdorf I tested by copying & pasting https://raw.githubusercontent.com/DavidAnderson684/FlexSlider/c99a33ad00cda3b0db768c40ee8c2b3ca53823e4/jquery.flexslider.js in-place of the plugin's existing `jquery.flexslider.min.js` file (doing a very minor version bump to the plugin to cache-bust the asset while still allowing it to update properly.)

This appears to not suffer from that issue. I also didn't see any problems with any of my other sliders/carousels (see https://cowv.amperage.dev). So it's looking good to me!

Thanks!

**Comment by KevinBatdorf** [comment]
Thanks @KZeni

**Pull request merged**
